# Generated by Django 5.1.4 on 2024-12-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.IntegerField()),
                ("homepage", models.URLField()),
                ("original_language", models.CharField(max_length=2)),
                ("original_title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
                ("revenue", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("production_company_id", models.IntegerField()),
                ("genre_id", models.IntegerField()),
                ("languages", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "movies",
            },
        ),
    ]
