# Generated by Django 5.1.4 on 2024-12-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
    ]
